### ISSUE TITLE
sass 中处理 calc() 函数中遇到的坑

### ISSUE THREAD

**Issue by jackPanyj** [jackPanyj/effective-javascript-#10]
虽然 `calc()` 的兼容性并不好， 用起来真心强大

不过在 `sass` 中计算 **函数** **变量** 等有一些坑， 比如：

``` css
  $font-30: 30px;
  h1 {
    font-size: calc(100px - $font-30)
  }
```

在上例中，`sass` 是无法正确的编译的， 它的输出是这样的：

``` css
$font-30: 30px;
h1 {
  font-size: calc(100px - $font-30)
}
```
### 解决方案：

``` scss
$font-30: 30px;
h1 {
  font-size: calc(100px - #{$font-30})
}
```

这样就可以得到我们预期的输出了。

同样的情况也适应于函数， 比如

``` scss
  @function r($px) {
    @return $px / 32 + rem;
  }
  h1 {
    font-size: calc(#{r(100)} - #{r(40)})
  }
```

[测试demo](http://www.sassmeister.com/gist/af3b9e03e8380183b3c2bf02fce08cef)

**Comment by jackPanyj** [comment]
虽然 `calc()` 的兼容性并不好， 用起来真心强大

不过却无法在 `sass` 中计算 **函数** **变量** 等， 比如：

``` css
  $font-30: 30px;
  h1 {
    font-size: calc(100px - $font-30)
  }
```

在上例中，`sass` 是无法正确的编译的， 它的输出是这样的：

``` css
$font-30: 30px;
h1 {
  font-size: calc(100px - $font-30)
}
```

### 解决方案：

``` scss
$font-30: 30px;
h1 {
  font-size: calc(100px - #{$font-30})
}
```
这样就可以得到我们预期的输出了。

同样的情况也适应于函数， 比如

``` scss
  @function r($px) {
    @return $px / 32 + rem;
  }
  h1 {
    font-size: calc(#{r(100)} - #{r(40)})
  }
```

[输出结果](http://www.sassmeister.com/gist/af3b9e03e8380183b3c2bf02fce08cef)
