### ISSUE TITLE
css 之 实现多重边框

### ISSUE THREAD

**Issue by jackPanyj** [jackPanyj/effective-javascript-#15]
其实实现多重边框也不是很难， 在外面套一个`div`就可以了。

**但，其实有时候改变页面的结构，会发生很多意想不到的事情，一般不建议用。**

这次介绍俩个属性来实现这一目标
1. `outline` 属性
   
   顾名思义这个属性就是专门添加外边框的， 跟 `border`的属性类似
   
   包含`outline-width`,  `outline-style`,  `outline-color`
   
   除此之外， `css3` 又新增了一个属性 `outline-offset` 表示偏移值， 可正可负， 举例：
   
   ``` css
   div.outline {
     width:100px;
     height: 100px;
     border: 10px solid teal;
     outline: 10px dashed pink;
     outline-offset: 10px;
   }
   ```
   
   [查看demo](http://codepen.io/jackpan/pen/mPYYEM)

这个方法确实不错， 不过有俩个缺点，

```
+  只能多加一个边框

+  当`border`为圆角的时候， 外（内）边框不会发生变化。
```
1. 使用`box-shadow`实现
   
   `box-shadow` 最多可接受六个个值：
   
   `/*inset | offset-x | offset-y | blur-radius | spread-radius | color */
   
   box-shadow: inset 2px 2px 2px 1px rgba(0, 0, 0, 0.2);
   `
   内阴影，x偏移量， y偏移量， 模糊半径， 伸展半径(可正可负)， 颜色。
   
   主要是靠第四个值，伸展半径来实现的。举例如下
   
   ``` css
   div.box-shadow {
       width: 100px;
       height: 100px;
       border: 10px solid teal;
       box-shadow: 0 0 0 10px pink;
   }
   ```

由于 `box-shadow`可以设置多个值， 所以就可以加多重边框了。

`box-shadow` 设置的边框也会随着`border-radius`的改变而改变， 完美解决了方案一中的俩个缺点。

不过方案一也有自己的优点， 比如可以设置外边框的`style` 为`dashed`， 距离调试方便。

[查看demo](http://codepen.io/jackpan/pen/mPYYEM) 
### 关于`box-shadow`的伸展半径为负数的情况， 请查看链接

[负数的伸展半径](https://github.com/doyoe/css-handbook/issues/99)

**Comment by jackPanyj** [comment]
其实实现多重边框也不是很难， 在外面套一个`div`就可以了。

但，其实有时候并改变页面的结构，会发生很多意想不到的事情。

这次介绍俩个属性来实现这一目标

1. `outline` 属性

顾名思义这个属性就是专门添加外边框的， 跟 `border`的属性类似

包含`outline-width`,  `outline-style`,  `outline-color`

除此之外， `css3` 又新增了一个属性 `outline-offset` 表示偏移值， 可正可负， 举例：

``` css
div.outline {
  width:100px;
  height: 100px;
  border: 10px solid teal;
  outline: 10px dashed pink;
  outline-offset: 10px;
}
```
[demo 地址]()

这个方法确实不错， 不过有俩个缺点，

 1. 只能多加一个边框
 2. 当`border`为圆角的时候， 外（内）边框不会发生变化。

2. 使用`box-shadow`实现
