### ISSUE TITLE
重写单选框按钮, 复选框按钮

### ISSUE THREAD

**Issue by jackPanyj** [jackPanyj/effective-javascript-#18]
感觉发现`ui`给我的图的单选框跟默认的差别好大。

又不能不听他的，没办法只能自己想办法做一个了。

原理： 利用`label`标签跟单选框关联， 隐藏单选框，用`label`的`：：before`模拟一个单选框

`html`代码：

``` html
<div class="row">
  <input type="radio" name="radio-1" id="radio-1"/>
  <label for="radio-1">每日一次</label>
</div>
<div class="row">
  <input type="radio" checked="checked" name="radio-1" id="radio-2"/>
  <label for="radio-2">每日多次</label>
</div>
```

scss 代码

``` scss
$blue: #51b8f2;
html {
    box-sizing: border-box;
}
*, *::before, *::after {
    box-sizing: inherit;
}
body {
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
    height: 100vh;
}
.row {
    margin: 20px;
    height: 40px;
}
input[type="radio"] {
    display: none;
    + label {
        position: relative;
    }

    + label::before {
        content: "";
        width: 10px;
        height: 10px;
        border-radius: 50%;
        border: 4px solid white;
        background-color: white;
        box-shadow: 0 0 0 1px #ebebeb;
        position: absolute;
        left: -20px;
        top: 50%;
        transform: translateY(-50%);
    }

    &:checked + label::before {
        border-color: $blue;
    }
}
```

效果图：
![](http://jackpanyj.github.io/blog_demo/img/input-radio.png)
## 复选框的重写跟单选框类似就不介绍了。 下面是demo地址

[查看单选框demo](http://codepen.io/jackpan/pen/rLaNRa)

[查看复选框demo](http://codepen.io/jackpan/pen/VjLyZm)

**Comment by jackPanyj** [comment]
感觉发现`ui`给我的图的单选框跟默认的差别好大。

又不能不听他的，没办法只能自己想办法做一个了。

原理： 利用`label`标签跟单选框关联， 隐藏单选框，用`label`的`：：before`模拟一个单选框

`html`代码：
```html
<div class="row">
  <input type="radio" name="radio-1" id="radio-1"/>
  <label for="radio-1">每日一次</label>
</div>
<div class="row">
  <input type="radio" checked="checked" name="radio-1" id="radio-2"/>
  <label for="radio-2">每日多次</label>
</div>
```

```scss
$blue: #51b8f2;
html {
	box-sizing: border-box;
}
*, *::before, *::after {
	box-sizing: inherit;
}
body {
	display: flex;
	justify-content: center;
	align-items: center;
	flex-direction: column;
	height: 100vh;
}
.row {
	margin: 20px;
	height: 40px;
}
input[type="radio"] {
	display: none;
	+ label {
		position: relative;
	}

	+ label::before {
		content: "";
		width: 10px;
		height: 10px;
		border-radius: 50%;
		border: 4px solid white;
		background-color: white;
		box-shadow: 0 0 0 1px #ebebeb;
		position: absolute;
		left: -20px;
		top: 50%;
		transform: translateY(-50%);
	}

	&:checked + label::before {
		border-color: $blue;
	}
}
```

效果图：
![](http://jackpanyj.github.io/blog_demo/img/input-radio.png)

### 虽然做的没那么炫酷， 但是没办法，这是`ui`的设计图。我只用了`::before`, 其实如果配合`::after`和一些`transition`动画的话会炫酷好多。

(查看demo)[http://codepen.io/jackpan/pen/rLaNRa]
