### ISSUE TITLE
用css3的渐变画出棋盘格

### ISSUE THREAD

**Issue by jackPanyj** [jackPanyj/effective-javascript-#19]
最近一直在看`css揭秘` 这本书，从中学到了很多，比如今天介绍的用`css`制作棋盘格

用到的知识点： `css渐变， background-size, background-position`

首先看一张效果图
![](http://blog.teemo.pub/blog_demo/img/chess.png)

`html` 代码如下：

``` html
<div class="chess"></div>
```

`css` 代码如下

``` css
.chess {
  height: 300px;
  width: 300px;
  border: 1px solid;
  background-image: linear-gradient(45deg, #000 25%, transparent 0, transparent 75%, #000 0),
                    linear-gradient(45deg, #000 25%, transparent 0, transparent 75%, #000 0);
  background-position: 0 0, 15px 15px;
  background-size: 30px 30px;
}
```

原理解释：

先画一个大小`30*30`的正方形然后沿45度分别在`0~25%`， `75%~100%`填充黑色， 然后利用背景平铺，铺满整个背景，
在原来的基础上又添加一层渐变，然后让这次的背景图的位置错开，即这次的右上角为上次的中心。这样形成了棋盘格。

扩展：
其实制作棋盘格最简单的方法是利用css4的锥形渐变`conic-gradient`， 不过现在还没有任何一个浏览器厂商实现了这个标准。

好在找到了一个`polyfill`， 代码如下

`html` 代码：

``` html
<div class="polyfill"></div>
<script src="http://leaverou.github.io/conic-gradient/conic-gradient.js" charset="utf-8"></script>
```

`css` 代码：

``` css
.polyfill {
  width: 300px;
  height: 300px;
  border: 1px solid;
  margin-left: 30px;
  background: conic-gradient(#000 25%, #fff 0 50%, #000 0 75%, #fff 0);
  background-size: 30px 30px;
}
```

[demo示例](http://codepen.io/jackpan/pen/XKNLgJ)

[参考链接](http://leaverou.github.io/conic-gradient/)

**Comment by jackPanyj** [comment]
最近一直在看`css揭秘` 这本书，从中学到了很多，比如今天介绍的用`css`制作棋盘格

用到的知识点： `css渐变， background-size, background-position`

首先看一张效果图
![]()

`html` 代码如下：
``` html
<div class="chess"></div>
```

`css` 代码如下
``` css
.chess {
  height: 300px;
  width: 300px;
  border: 1px solid;
  background-image: linear-gradient(45deg, #000 25%, transparent 0, transparent 75%, #000 0),
                    linear-gradient(45deg, #000 25%, transparent 0, transparent 75%, #000 0);
  background-position: 0 0, 15px 15px;
  background-size: 30px 30px;
}
```

原理解释：

先画一个大小`30*30`的正方形然后沿45度分别在`0~25%`， `75%~100%`填充黑色， 然后利用背景平铺，铺满整个背景，
在原来的基础上又添加一层渐变，然后让这次的背景图的位置错开，即这次的右上角为上次的中心。这样形成了棋盘格。


扩展：
其实制作棋盘格最简单的方法是利用css4的锥形渐变`conic-gradient`， 不过现在还没有任何一个浏览器厂商实现了这个标准。

好在找到了一个`polyfill`， 代码如下

`html` 代码：

``` html
<div class="polyfill"></div>
<script src="http://leaverou.github.io/conic-gradient/conic-gradient.js" charset="utf-8"></script>
```

`css` 代码：

``` css
.polyfill {
  width: 300px;
  height: 300px;
  border: 1px solid;
  margin-left: 30px;
  background: conic-gradient(#000 25%, #fff 0 50%, #000 0 75%, #fff 0);
  background-size: 30px 30px;
}
```

[demo示例](http://codepen.io/jackpan/pen/XKNLgJ)

[参考链接](http://leaverou.github.io/conic-gradient/)
