### ISSUE TITLE
css 实现蚂蚁行军的特效

### ISSUE THREAD

**Issue by jackPanyj** [jackPanyj/effective-javascript-#20]
先来一张效果图
![](https://jackpanyj.github.io/blog_demo/img/ant.png)

图是静态的，真正的效果应该是动态的。

先上代码：

`html` 部分：

``` html
<div class="ant">蚂蚁行军</div>
```

`css` 部分：

``` css
body {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
}
.ant {
  display: flex;
  justify-content: center;
  align-items: center;
  font-size: 50px;
  color: #00f;
  height: 300px;
  width: 300px;
  background-image: linear-gradient(#fff, #fff), repeating-linear-gradient(-45deg, currentColor 0, currentColor 10px, transparent 0, transparent 20px);
  background-clip: padding-box, border-box;
  border: 1px solid transparent;
  background-origin: border-box;
  animation: ant 12s infinite linear;
  background-size: 30px 30px;
}

@keyframes ant {
  to {
    background-position: 100% 100%;
  }
}
```

代码解释：
1. 首先声明一点 `background-image` 如果存在多个图片的话， 其表现是前面的覆盖后面的。
2. 用`linear-gradient(#fff, #fff)`做出白色的背景图作为第一个`background-image`
3. 用 `repeating-linear-gradient(-45deg, currentColor 0, currentColor 10px, transparent 0, transparent 20px)`
   做出一个字体色与透明色间隔图案，作为第二个背景图
4. 利用`background-clip`分别剪切俩个背景图， 第一个为`padding-box`, 第二个为 `border-box`
5. 设置`border`为`1px`， 背景色为透明色，这样就得到了一个静态的1px的边框
6. 设置`background-size` 为合适的尺寸
7. 制作动画帧， 然`background-position`慢慢移动到100%
8. 应用动画，设置合适的时间间隔

[demo链接](http://codepen.io/jackpan/pen/YWZGvj)

**Comment by jackPanyj** [comment]
先来一张效果图
![]()

图是静态的，真正的效果应该是动态的。

先上代码：

`html` 部分：

``` html
<div class="ant">蚂蚁行军</div>
```

`css` 部分：

``` css
body {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
}
.ant {
  display: flex;
  justify-content: center;
  align-items: center;
  font-size: 50px;
  color: #00f;
  height: 300px;
  width: 300px;
  background-image: linear-gradient(#fff, #fff), repeating-linear-gradient(-45deg, currentColor 0, currentColor 10px, transparent 0, transparent 20px);
  background-clip: padding-box, border-box;
  border: 1px solid transparent;
  background-origin: border-box;
  animation: ant 12s infinite linear;
  background-size: 30px 30px;
}

@keyframes ant {
  to {
    background-position: 100% 100%;
  }
}
```

代码解释：

1. 首先声明一点 `background-image` 如果存在多个图片的话， 其表现是前面的覆盖后面的。
2. 用`linear-gradient(#fff, #fff)`做出白色的背景图作为第一个`background-image`
3. 用 `repeating-linear-gradient(-45deg, currentColor 0, currentColor 10px, transparent 0, transparent 20px)`
   做出一个字体色与透明色间隔图案，作为第二个背景图
4. 利用`background-clip`分别剪切俩个背景图， 第一个为`padding-box`, 第二个为 `border-box`
5. 设置`border`为`1px`， 背景色为透明色，这样就得到了一个静态的1px的边框
6. 设置`background-size` 为合适的尺寸
7. 制作动画帧， 然`background-position`慢慢移动到100%
8. 应用动画，设置合适的时间间隔
