### ISSUE TITLE
css实现无滚动条的滚动

### ISSUE THREAD

**Issue by jackPanyj** [jackPanyj/effective-javascript-#27]
### 突然遇到一个难题， 就是实现无滚动条的滚动

这样的滚动靠的是鼠标上的滚轮，利用滚轮来滚动，

其实就是正常的滚动，去掉滚动条。

在`webkit`内核的浏览器中有个私有属性`::-webkit-scrollbar`，可以对滚动条进行样式的设置的，

不过也只针对`webkit`内核的浏览器，，，

下面介绍两种实现方法， 其思路都是一样的，  #先看代码

html 代码：

``` html
<div class="box1">
  <div class="box2">
    <p>ddddd</p>
    <p>ddddd</p>
    <p>ddddd</p>
    <p>ddddd</p>
    <p>ddddd</p>
    <p>ddddd</p>
    <p>ddddd</p>
    <p>ddddd</p>
    <p>ddddd</p>
    <p>ddddd</p>
    <p>ddddd</p>
    <p>ddddd</p>
    <p>ddddd</p>
    <p>ddddd</p>
    <p>ddddd</p>
    <p>ddddd</p>
  </div>
</div>
```

css 代码：

``` css
body {
  display: flex;
  height: 100vh;
}
.box1 {
  height: 20%;
  width: 20%;
  border: 1px solid #008080;
  margin: auto;
  overflow: hidden;
}
.box2 {
  box-sizing: content-box;
  height: 100%;
  padding-right: 17px;
  width: 100%;
  overflow: auto;
}
```

原理解释：

用另一个`box1`去包裹原来的`box2`， 把`box1`的`overflow` 设置为`hidden`。

其实第二个是有滚动条的， 只不过滚动条的部分超出了`box2`， 然后被`box1`隐藏了。

至于让滚动条溢出的做法是：

设置`box-sizing`为`content-box`, 然后利用`padding-right`把滚动条挤出去。

一般浏览器的滚动条的宽度应该就是`17px`吧

这样就完美实现了无滚动条的滚动。

[查看demo](http://codepen.io/jackpan/pen/NAEbvO)

方法二： 利用绝对定位让`box2`的滚动条溢出

html代码同上

css 代码：

``` css
body {
  display: flex;
  height: 100vh;
}
.box1 {
  height: 20%;
  width: 20%;
  border: 1px solid #008080;
  margin: auto;
  overflow: hidden;
  position: relative;
}
.box2 {
  box-sizing: border-box;
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: -17px;
  overflow: auto;
}
```

[查看demo](http://codepen.io/jackpan/pen/AXmpNE)
### 顺便说一句：

一般来说滚动条占的宽度为`17px`，但是这只是经验所得， 并不精确，如果想要精确的话，就需要用`js`计算了。

`var scrollBarLength = element.offsetWidth - element.clientWidth - 2 * element.borderWidth`

`offsetWidth` 包括`content`, `padding`, `border`, `scroll bar` 的宽度

`clientWidth` 包括`content`, `padding` 的宽度
