### ISSUE TITLE
one div demos

### ISSUE THREAD

**Issue by jackPanyj** [jackPanyj/effective-javascript-#32]
### 闲着没事写了写`css` 都是用一个div实现的， 具体示例如下：
1. 一个 `div` 点缀随机点
   
   效果图：
   ![](http://7xsn63.com2.z0.glb.clouddn.com/random.png)
   
   html 代码：
   
   ``` html
     <div class="stars"></div>
   ```
   
   scss 代码：
   
   ``` sass
     @function multiple-box-shadow ($n) {
         $value: '#{random(1000)}px #{random(1000)}px #A1B8D0';
         @for $i from 2 through $n {
             $value: '#{$value} , #{random(1000)}px #{random(1000)}px #A1B8D0';
         }
         @return unquote($value);
     }
     .stars {
         width: 2px;
         height: 2px;
         position: absolute;
         top: 0;
         left: 0;
         background-color: transparent;
         box-shadow: multiple-box-shadow(500)
     }
   ```
   
   [demo](http://codepen.io/jackpan/pen/RGkqkK)
2. 一个 `div` 做的下划线
   
   效果图：
   ![](http://7xsn63.com2.z0.glb.clouddn.com/hover-underline.png)
   
   html 代码：
   
   ``` html
     <div class="underline">hover me to see underline</div>
   ```
   
   scss 代码：
   
   ``` sass
     .underline {
       cursor: pointer;
       margin: auto;
       font-size: 30px;
       line-height: 30px;
       padding: 10px;
       border-radius: 5px;
       background: linear-gradient(transparent 70%, teal 0) no-repeat center left / 0 100%;
       transition: background-size .5s ease;
       &:hover {
         background-size: 100% 100%;
       }
     }
   ```
   
   [demo](http://codepen.io/jackpan/pen/bwLPAd)
3. 一个 `div` 做的矩形平分
   
   效果图：
   ![](http://7xsn63.com2.z0.glb.clouddn.com/rect-divider.png)
   
   html 代码：
   
   ``` html
   <div class="rect triangle"></div>
   <div class="rect trapezoid"></div>
   ```
   
   scss 代码：
   
   ``` scss
   .rect {
    margin: auto;
    height: 100px;
    width: 400px;
    border: 1px solid #008080;
   }
   .triangle {
    background-image: linear-gradient(194deg, #f00 0, #f00 50%, transparent 50%), linear-gradient(194deg, #00f 50%, #00f 100%);
   }
   .trapezoid {
    background-image: linear-gradient(145deg, #f00 0, #f00 50%, transparent 50%), linear-gradient(145deg, #00f 50%, #00f 100%);
   }
   ```
   
   [demo](http://codepen.io/jackpan/pen/kkyRZo)
4. 一个 `div` 做的宇宙飞船
   
   效果图：
   ![](http://7xsn63.com2.z0.glb.clouddn.com/spaceboat.png)
   
   html 代码：
   
   ``` html
     <div class="boat"></div>
   ```
   
   scss 代码：
   
   ``` scss
     $size: 300px;
     .boat {
       margin: auto;
       height: $size;
       width: $size;
       border-radius: 50%;
       position: relative;
       background-color: teal;
       &::before, &::after{
         content: '';
         position: absolute;
         width: $size * 1.2;
         height: $size * .2;
         border: $size * .2 solid gray;
         border-radius: 50%;
         top: 50%;
         left: 50%;
         transform: translate(-50%, -50%) rotateX(58deg) rotateY(146deg);
       }
       &::before {
         border-top-color: transparent;
         border-left-color: transparent;
       }
       &:after {
         z-index: -1;
       }
     }
   ```
   
   [demo](http://codepen.io/jackpan/pen/LRjpRG)
5. 一个 `div` 做的帮助提示
   
   效果图:
   ![](http://7xsn63.com2.z0.glb.clouddn.com/help-icon.png)
   
   html 代码：
   
   ``` html
     <div class="help"></div>
   ```
   
   scss 代码：
   
   ``` scss
     @mixin text-multi-lines {
       margin-top: -.25em;
       margin-bottom: -.25em;
       line-height: 1.5;
     }
     .help {
       position: relative;
       cursor: pointer;
       width: 20px;
       height: 20px;
       border: 1px solid teal;
       border-radius: 50%;
       text-align: center;
       line-height: 20px;
       color: teal;
       margin-bottom: 20px;
       &::before {
         content: attr(content);
         position: absolute;
         display: none;
         bottom: calc(16px + 8px + 14px);
         left: 50%;
         transform: translateX(-50%);
         width: 360px;
         padding: 10px;
         font-size: 12px;
         border: 1px solid #ebebeb;
         border-radius: 4px;
         background-color: #fff;
         box-shadow: 0 5px 10px -2px rgba(0, 0, 0, .2);
         @include text-multi-lines;
       }
       &:hover::before, &:hover::after {
         display: block;
       }
       &::after {
         content: '';
         position: absolute;
         display: none;
         left: 50%;
         transform: translateX(-50%) rotate(45deg);
         width: 20px;
         height: 20px;
         border-right: 1px solid #ebebeb;
         border-bottom: 1px solid #ebebeb;
         border-radius: 4px;
         background-color: #fff;
         box-shadow: 5px 5px 10px -2px rgba(0, 0, 0, .2);
         bottom: 26px;
       }
     }
   ```
   
   [demo](http://codepen.io/jackpan/pen/KMMdZM)
6. 一个 `div` 做的八卦
   
   效果图：
   ![](http://7xsn63.com2.z0.glb.clouddn.com/bagua.png)
   
   html 代码：
   
   ``` html
     <div class="yinyang"></div>
   ```
   
   scss 代码：
   
   ``` scss
     @keyframes rotate {
       0% { transform: rotate(0); }
       100% { transform: rotate(360deg); }
     };
     $size: 10rem;
     .yin-yang {
       margin: auto;
       height: $size;
       width: $size;
       border-radius: 50%;
       background: linear-gradient(to bottom, #fff 0%, #fff 50%, #000 50%, #000 100%);
       box-shadow: 0 0 1rem rgba(0, 0, 0, .4);
       animation: rotate 5s linear infinite;
   
       &:before, &:after {
           content: '';
           box-sizing: border-box;
           position: absolute;
           top: 50%;
           transform: translateY(-50%);
           height: 50%;
           width: 50%;
           border-radius: 50%;
       }
   
       &:before {
           left: 0;
           background: #FFF;
           border: $size/5 solid #000;
       }
   
       &:after {
           right: 0;
           background: #000;
           border: $size/5 solid #fff;
       }
     }
   ```
   
   [demo](http://codepen.io/jackpan/pen/KgvdJL)
