### ISSUE TITLE
sass中$variable-#{$variable} 不支持的替代方法

### ISSUE THREAD

**Issue by jackPanyj** [jackPanyj/effective-javascript-#33]
本来的 `sass` 是这样的

``` scss
$card-red: #d0262f;
$card-blue: #51b8f2;
$card-orange: #fb8649;
$card-green: #77e1bb;
$card-gray: #969696;
.card-red {
  border-left-color: $card-red;
  .good-title {
    color: $card-red;
  }
}
.card-blue {
  border-left-color: $card-blue;
  .good-title {
    color: $card-blue;
  }
}
.card-green {
  border-left-color: $card-green;
  .good-title {
    color: $card-green;
  }
}
.card-orange {
  border-left-color: $card-orange;
  .good-title {
    color: $card-orange;
  }
}
```

看着结构写多了真心蛋疼，，突然想到`sass`中还有循环这一说法，就去试了一下，代码如下

``` scss
$list: red blue green orange;

@each $color in $list {
  .card-#{$color} {
    border-left-color: $card-#{$color};
    .good-title {
      color: $card-#{$color}
    }
  }
}
```

无奈报错，原因是因为`$card-#{$color}`无法正常编译

便试着将 `$card-#{$color}`改成了 unquote('$card-#{$color}'),

虽然没有报错，但是输出为 `border-left-color: $card-red` 等，顿时懵逼了。。

后来谷歌了一番终于找到了一个解决方案，就是使用 `sass` 中的 `map` 类型代替 `list` 类型

``` scss
$map: (red: $card-red, blue: $card-blue, green: $card-green, orange: $card-orange);
@each $key, $val in $map {
  .card-#{$key} {
    border-left-color: $val;
    .good-title {
      color: $val;
    }
  }
}
```

总算完美解决了这个问题。

[参考链接](https://github.com/sass/sass/issues/132)
