### ISSUE TITLE
css 利用radial-gradient（） 实现内凹角

### ISSUE THREAD

**Issue by jackPanyj** [jackPanyj/effective-javascript-#8]
效果图如下：

![](http://jackpanyj.github.io/blog_demo/img/css-radius-in.png)

实现方式：

``` css
div.img {
width: 200px;
height: 200px;
background-image: radial-gradient( top right, #fff 10%, transparent 10%),
                  radial-gradient( top left, #fff 10%, transparent 10%),
                  radial-gradient( bottom left, #fff 10%, transparent 10%),
                  radial-gradient( bottom right, #fff 10%, transparent 10%);
background-color: blue;
}
```

解释原理：

四个边其实是四个径向渐变， 圆心都设在了四个顶点

半径为正方形对角线长度的百分之十，

如果想要固定像素， 比如20px的半径则

``` css
  radial-gradient(200px at top right, #fff 10%, transparent 10%)
```
### 遇到的坑

**最后的那个颜色值一定要为`transparent`, 如果设置为 `#fff` 的话， 只有一个角生效。其他的三个都会被覆盖。**

[`codpen` 的链接地址](http://codepen.io/jackpan/pen/LNqQzB)

**Comment by jackPanyj** [comment]
效果图如下：

![](jackpanyj.github.io/blog_demo/img/css-radius-in.png)

**Comment by jackPanyj** [comment]
效果图如下：

![](http://jackpanyj.github.io/blog_demo/img/css-radius-in.png)

实现方式：

``` css
div.img {
width: 200px;
height: 200px;
background-image: radial-gradient( top right, #fff 10%, transparent 10%),
                  radial-gradient( top left, #fff 10%, transparent 10%),
                  radial-gradient( bottom left, #fff 10%, transparent 10%),
                  radial-gradient( bottom right, #fff 10%, transparent 10%);
background-color: blue;
}
```

解释原理：

四个边其实是四个径向渐变， 圆心都设在了四个顶点

半径为正方形对角线长度的百分之十，

如果想要固定像素， 比如20px的半径则

``` css
  radial-gradient(200px at top right, #fff 10%, transparent 10%)
```

### 遇到的坑

**最后的那个颜色值一定要为`transparent`, 如果设置为 `#fff` 的话， 只有一个角生效。其他的三个都会被覆盖。**

[`codpen` 的链接地址](http://codepen.io/jackpan/pen/LNqQzB)

**Comment by jackPanyj** [comment]
效果图如下：

![](http://jackpanyj.github.io/blog_demo/img/css-radius-in.png)

实现方式：

``` css
div.img {
width: 200px;
height: 200px;
background-image: radial-gradient( top right, #fff 10%, transparent 10%),
                  radial-gradient( top left, #fff 10%, transparent 10%),
                  radial-gradient( bottom left, #fff 10%, transparent 10%),
                  radial-gradient( bottom right, #fff 10%, transparent 10%);
background-color: blue;
}
```

解释原理：

四个边其实是四个径向渐变， 圆心都设在了四个顶点

半径为正方形对角线长度的百分之十，

如果想要固定像素， 比如20px的半径则

``` css
  radial-gradient(200px at top right, #fff 10%, transparent 10%)
```

### 遇到的坑

**最后的那个颜色值一定要为`transparent`, 如果设置为 `#fff` 的话， 只有一个角生效。其他的三个都会被覆盖。**

[`codpen` 的链接地址](http://codepen.io/jackpan/pen/LNqQzB) 

<p data-height="265" data-theme-id="0" data-slug-hash="LNqQzB" data-default-tab="css,result" data-user="jackpan" data-embed-version="2" class="codepen">See the Pen <a href="http://codepen.io/jackpan/pen/LNqQzB/">LNqQzB</a> by 潘家大少爷 (<a href="http://codepen.io/jackpan">@jackpan</a>) on <a href="http://codepen.io">CodePen</a>.</p>
<script async src="//assets.codepen.io/assets/embed/ei.js"></script>
